title: Summer Research for Intl Students # (Maintained by @mianzg)
# email: mian.zhong@berkeley.edu
description: Countdowns to eligible summer cs/math research opportunities deadlines
author: Mian Zhong

domain: "intlstd-su-research.es"
baseurl: ""

twitter_username: 
twitter_hashtag: 
github_username: mianzg
github_repo: intlstd-su-research

markdown: kramdown
ga_id: UA-36274081-2
